// ---***---
// This file generate paths to all images/gifs that are inside the assets folder
// Those images will be then cached
// It takes all folders declared in the imageFolders array, and saves all file with appropriate extensions
// --
// If in the future more images would be imported or changed, then this script should be run once again
//  to update all paths inside the generatedImagePathArray file.
// Otherwise, the paths generated before do not need to be updated

const fs = require("fs");
const path = require("path");

// Declare the folders' names
const imageFolders = [
  "HomeScreen",
  "ABSExercises",
  "ArmsExercises",
  "LegsExercises",
  "YogaExercises",
  "Others",
];

const generateImagePaths = (folder) => {
  const imageFolderPath = path.join(__dirname, "assets", folder);

  const files = fs.readdirSync(imageFolderPath);

  // Collect all files that end with those extensions
  return files
    .filter(
      (file) =>
        file.endsWith(".png") ||
        file.endsWith(".jpg") ||
        file.endsWith(".webp") ||
        file.endsWith(".gif")
    )
    .map((file) => `require('./assets/${folder}/${file}')`);
};

const imagePaths = imageFolders
  .map((folder) => generateImagePaths(folder))
  .flat();

// Genrate the file with paths
const content = `
  // Auto-generated by generateImagePathArray.js
  export default [
    ${imagePaths.join(",\n      ")}
  ];
`;

// Save them to this file
fs.writeFileSync(path.join(__dirname, "generatedImagePathArray.js"), content);
console.log("Image array generated successfully.");
