
    // Auto-generated by generateImageArray.js
    export default [
      require('./assets/HomeScreen/abs-workout.jpg'),
      require('./assets/HomeScreen/abs-workout1.jpg'),
      require('./assets/HomeScreen/arms-workout.png'),
      require('./assets/HomeScreen/fbw-workout.jpg'),
      require('./assets/HomeScreen/legs-workout.png'),
      require('./assets/HomeScreen/yoga-workout.png')
    ];
  