const fs = require("fs");
const path = require("path");

const imageFolderPath = path.join(__dirname, "assets", "HomeScreen");

fs.readdir(imageFolderPath, (err, files) => {
  if (err) {
    console.error("Error reading image folder:", err);
    return;
  }

  const imagePaths = files
    .filter((file) => file.endsWith(".png") || file.endsWith(".jpg"))
    .map((file) => `require('./assets/HomeScreen/${file}')`);

  const content = `
    // Auto-generated by generateImageArray.js
    export default [
      ${imagePaths.join(",\n      ")}
    ];
  `;

  fs.writeFileSync(path.join(__dirname, "generatedImageArray.js"), content);
  console.log("Image array generated successfully.");
});
